/* Generated from original Scripts/scriptcommands.h; do not edit. */
#ifndef RENEGADE_CAMPAIGN_SCRIPT_DEFAULTS_H
#define RENEGADE_CAMPAIGN_SCRIPT_DEFAULTS_H
#include "renegade_script_call_defaults.h"

#define RENEGADE_CAMPAIGN_ADD_OBJECTIVE_4(a0, a1, a2, a3) Add_Objective(a0, a1, a2, a3, NULL, 0)
#define RENEGADE_CAMPAIGN_ADD_OBJECTIVE_5(a0, a1, a2, a3, a4) Add_Objective(a0, a1, a2, a3, a4, 0)
#define RENEGADE_CAMPAIGN_ADD_OBJECTIVE_6(a0, a1, a2, a3, a4, a5) Add_Objective(a0, a1, a2, a3, a4, a5)
#define RENEGADE_CAMPAIGN_ADD_OBJECTIVE_SELECT(_a0, _a1, _a2, _a3, _a4, _a5, NAME, ...) NAME
#define Add_Objective(...) RENEGADE_CAMPAIGN_ADD_OBJECTIVE_SELECT(__VA_ARGS__, RENEGADE_CAMPAIGN_ADD_OBJECTIVE_6, RENEGADE_CAMPAIGN_ADD_OBJECTIVE_5, RENEGADE_CAMPAIGN_ADD_OBJECTIVE_4)(__VA_ARGS__)

#define RENEGADE_CAMPAIGN_CREATE_EXPLOSION_2(a0, a1) Create_Explosion(a0, a1, NULL)
#define RENEGADE_CAMPAIGN_CREATE_EXPLOSION_3(a0, a1, a2) Create_Explosion(a0, a1, a2)
#define RENEGADE_CAMPAIGN_CREATE_EXPLOSION_SELECT(_a0, _a1, _a2, NAME, ...) NAME
#define Create_Explosion(...) RENEGADE_CAMPAIGN_CREATE_EXPLOSION_SELECT(__VA_ARGS__, RENEGADE_CAMPAIGN_CREATE_EXPLOSION_3, RENEGADE_CAMPAIGN_CREATE_EXPLOSION_2)(__VA_ARGS__)

#define RENEGADE_CAMPAIGN_FIND_CLOSEST_SOLDIER_3(a0, a1, a2) Find_Closest_Soldier(a0, a1, a2, true)
#define RENEGADE_CAMPAIGN_FIND_CLOSEST_SOLDIER_4(a0, a1, a2, a3) Find_Closest_Soldier(a0, a1, a2, a3)
#define RENEGADE_CAMPAIGN_FIND_CLOSEST_SOLDIER_SELECT(_a0, _a1, _a2, _a3, NAME, ...) NAME
#define Find_Closest_Soldier(...) RENEGADE_CAMPAIGN_FIND_CLOSEST_SOLDIER_SELECT(__VA_ARGS__, RENEGADE_CAMPAIGN_FIND_CLOSEST_SOLDIER_4, RENEGADE_CAMPAIGN_FIND_CLOSEST_SOLDIER_3)(__VA_ARGS__)

#define RENEGADE_CAMPAIGN_GRANT_KEY_2(a0, a1) Grant_Key(a0, a1, true)
#define RENEGADE_CAMPAIGN_GRANT_KEY_3(a0, a1, a2) Grant_Key(a0, a1, a2)
#define RENEGADE_CAMPAIGN_GRANT_KEY_SELECT(_a0, _a1, _a2, NAME, ...) NAME
#define Grant_Key(...) RENEGADE_CAMPAIGN_GRANT_KEY_SELECT(__VA_ARGS__, RENEGADE_CAMPAIGN_GRANT_KEY_3, RENEGADE_CAMPAIGN_GRANT_KEY_2)(__VA_ARGS__)

#define RENEGADE_CAMPAIGN_MODIFY_ACTION_3(a0, a1, a2) Modify_Action(a0, a1, a2, true, true)
#define RENEGADE_CAMPAIGN_MODIFY_ACTION_4(a0, a1, a2, a3) Modify_Action(a0, a1, a2, a3, true)
#define RENEGADE_CAMPAIGN_MODIFY_ACTION_5(a0, a1, a2, a3, a4) Modify_Action(a0, a1, a2, a3, a4)
#define RENEGADE_CAMPAIGN_MODIFY_ACTION_SELECT(_a0, _a1, _a2, _a3, _a4, NAME, ...) NAME
#define Modify_Action(...) RENEGADE_CAMPAIGN_MODIFY_ACTION_SELECT(__VA_ARGS__, RENEGADE_CAMPAIGN_MODIFY_ACTION_5, RENEGADE_CAMPAIGN_MODIFY_ACTION_4, RENEGADE_CAMPAIGN_MODIFY_ACTION_3)(__VA_ARGS__)

#define RENEGADE_CAMPAIGN_SET_INNATE_SOLDIER_HOME_LOCATION_2(a0, a1) Set_Innate_Soldier_Home_Location(a0, a1, 999999)
#define RENEGADE_CAMPAIGN_SET_INNATE_SOLDIER_HOME_LOCATION_3(a0, a1, a2) Set_Innate_Soldier_Home_Location(a0, a1, a2)
#define RENEGADE_CAMPAIGN_SET_INNATE_SOLDIER_HOME_LOCATION_SELECT(_a0, _a1, _a2, NAME, ...) NAME
#define Set_Innate_Soldier_Home_Location(...) RENEGADE_CAMPAIGN_SET_INNATE_SOLDIER_HOME_LOCATION_SELECT(__VA_ARGS__, RENEGADE_CAMPAIGN_SET_INNATE_SOLDIER_HOME_LOCATION_3, RENEGADE_CAMPAIGN_SET_INNATE_SOLDIER_HOME_LOCATION_2)(__VA_ARGS__)

#define RENEGADE_CAMPAIGN_START_CONVERSATION_1(a0) Start_Conversation(a0, 0)
#define RENEGADE_CAMPAIGN_START_CONVERSATION_2(a0, a1) Start_Conversation(a0, a1)
#define RENEGADE_CAMPAIGN_START_CONVERSATION_SELECT(_a0, _a1, NAME, ...) NAME
#define Start_Conversation(...) RENEGADE_CAMPAIGN_START_CONVERSATION_SELECT(__VA_ARGS__, RENEGADE_CAMPAIGN_START_CONVERSATION_2, RENEGADE_CAMPAIGN_START_CONVERSATION_1)(__VA_ARGS__)

#endif
